// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6rjD8jLaUt0kH1R5DN70zhwjKraz1to',
    appId: '1:687633959068:android:22c661c164f22a0c9e8559',
    messagingSenderId: '687633959068',
    projectId: 'fir-test-project-4b356',
    storageBucket: 'fir-test-project-4b356.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgXeVgHUyECZvofSb7ZvCTQ5qIMbkCI84',
    appId: '1:687633959068:ios:f87ec3bfe4890c8b9e8559',
    messagingSenderId: '687633959068',
    projectId: 'fir-test-project-4b356',
    storageBucket: 'fir-test-project-4b356.firebasestorage.app',
    androidClientId: '687633959068-aik601nnh1v8iohmeeh1pouk2uck8rj5.apps.googleusercontent.com',
    iosClientId: '687633959068-c53tq4t1nfaped5ue19t1ibh00o305kb.apps.googleusercontent.com',
    iosBundleId: 'com.elgendy.blogfirebase',
  );
}
